In [1]:
import pandas as pd
import numpy as np

In [4]:

N = 4   # no of variable, as an example one reservoir and 3 nodes
corr_demands = 0.7 # correlation among demands
corr_reservoir_nodes = 0.001  # correlation among demands and reservoir head (almost no correlation)

mat_corr = np.zeros((N,N)) # initializing matrix

mat = np.full((N-1,N-1),corr_demands) # step 1 for a symmetric matrix of n-1 by n-1
mat_symm = (mat + mat.T)/2           # step 2

diag = np.ones(N)   # setting up the diagonal matrix, variance of nodal demands
np.fill_diagonal(mat_symm,diag)    
mat_corr[1:,1:] = mat_symm

mat_corr[0,0] = 1          # element (0,0) which is variance of resevoir head

top = np.full((N-1),corr_reservoir_nodes) # covariance between reservoir head and nodal demands
mat_corr[0,1:]=top
mat_corr[1:,0]=top

In [5]:
mat_corr

array([[1.e+00, 1.e-04, 1.e-04, 1.e-04],
       [1.e-04, 1.e+00, 7.e-01, 7.e-01],
       [1.e-04, 7.e-01, 1.e+00, 7.e-01],
       [1.e-04, 7.e-01, 7.e-01, 1.e+00]])

In [8]:
# Standard deviations
values = np.array([200,0.003,0.005,0.009])
std_devs = values*.2

In [9]:
std_devs

array([4.0e+01, 6.0e-04, 1.0e-03, 1.8e-03])

In [10]:
Diag = np.diag(std_devs)

In [11]:
Diag

array([[4.0e+01, 0.0e+00, 0.0e+00, 0.0e+00],
       [0.0e+00, 6.0e-04, 0.0e+00, 0.0e+00],
       [0.0e+00, 0.0e+00, 1.0e-03, 0.0e+00],
       [0.0e+00, 0.0e+00, 0.0e+00, 1.8e-03]])

In [12]:
cov_mat = Diag * mat_corr * Diag

In [13]:
cov_mat

array([[1.60e+03, 0.00e+00, 0.00e+00, 0.00e+00],
       [0.00e+00, 3.60e-07, 0.00e+00, 0.00e+00],
       [0.00e+00, 0.00e+00, 1.00e-06, 0.00e+00],
       [0.00e+00, 0.00e+00, 0.00e+00, 3.24e-06]])